---
title: Error Handling
description: Learn more about how to handle errors in CallApi
icon: ShieldAlert
---

## Error Object Structure

CallApi by default returns request and response errors as a value, wrapped in a single `error` object. This error object has three properties:

1. **name**: The name of the error (e.g., `'HTTPError'`, `'ValidationError'`, `'TypeError'`, `'SyntaxError'`)

2. **message**: A brief description of what went wrong:

   - For non-HTTP errors: The error message from the JavaScript error object
   - For HTTP errors: The error message from the server, or if not provided, falls back to the `defaultErrorMessage` option

3. **errorData**: The detailed error information:
   - For HTTP errors: The parsed response from the API
   - For validation errors: The validation issues array
   - For non-HTTP errors: The JavaScript error object that caused the error

```ts twoslash title="api.ts"
import { callApi } from "@zayne-labs/callapi";

const { error } = await callApi("https://my-api.com/api/v1/session");
// @annotate: Hover over the error object to see the type
```

## ErrorData Type

For HTTP errors, you can customize the error response data type by providing a second generic type argument to callApi:

```ts twoslash title="api.ts"
import { callApi } from "@zayne-labs/callapi";

type ErrorData = {
	message: string;
	errors: Array<string | string[]>;
};

const { error } = await callApi<unknown, ErrorData>("/api/endpoint");

if (error) {
	console.log(error.errorData); // Type is ErrorData
}
```

## The `error` object as a discriminated union

The error object returned from `callApi` is a discriminated union. You can use the `isHTTPError` utility from `@zayne-labs/callapi/utils` to check if it's an HTTP error:

```ts twoslash title="api.ts"
import { callApi } from "@zayne-labs/callapi";
import { isHTTPError } from "@zayne-labs/callapi/utils";

type UserData = {
	id: number;
	userId: string;
	title: string;
	completed: boolean;
};

type ErrorResponseData = {
	message?: string;
	errors?: Array<string | string[]>;
};

const { data, error } = await callApi<UserData, ErrorResponseData>("https://my-api.com/api/v1/session");

// @annotate: Hover over the error object to see its type narrowed specifically to HTTPError union
if (isHTTPError(error)) {
	console.error(error);

	console.error(error.name); // 'HTTPError'
	console.error(error.message);
	console.error(error.errorData); // Will be set to the error response data
}

if (error) {
	console.error(error);
	console.error(error.name); // PossibleValidationErrorName | PossibleJavascriptErrorNames
	console.error(error.message);
	console.error(error.errorData); // Will be set to the original error object that caused the error if it's a javascript error or the issues array if it's a validation error
}
```

If you want to handle validation errors specifically, you can use the `isValidationError` utility:

```ts twoslash title="api.ts"
import { callApi } from "@zayne-labs/callapi";
import { isValidationError } from "@zayne-labs/callapi/utils";

const { data, error } = await callApi("https://my-api.com/api/v1/session");

if (isValidationError(error)) {
	console.error(error);
	console.error(error.name); // 'ValidationError'
	console.error(error.message);
	console.error(error.errorData); // Will be set to the validation issues array
}
```

## Handling Thrown Errors

When using the `throwOnError` option, CallApi will throw any error it encounters instead of returning it. The thrown error can be an instance of the `HTTPError` class (a subclass of `Error`) or a `ValidationError` class (a subclass of `Error`) or a regular javascript error. You can handle `HTTPError` and `ValidationError` in a try-catch block using the `isHTTPErrorInstance` or `isValidationErrorInstance` utility respectively:

```ts twoslash title="api.ts"
import { callApi } from "@zayne-labs/callapi";
import { isHTTPErrorInstance, isValidationErrorInstance } from "@zayne-labs/callapi/utils";

type UserData = {
	id: number;
	userId: string;
	title: string;
	completed: boolean;
};

type ErrorResponseData = {
	message?: string;
	errors?: Array<string | string[]>;
};

try {
	const { data } = await callApi<UserData>("https://my-api.com/api/v1/session", {
		throwOnError: true,
	});
} catch (error) {
	if (isHTTPErrorInstance<ErrorResponseData>(error)) {
		console.error(error);
		console.error(error.name);
		console.error(error.message);
		console.error(error.errorData);
	}

	if (isValidationErrorInstance(error)) {
		console.error(error);
		console.error(error.name);
		console.error(error.message);
		console.error(error.errorData);
	}
}
```

This approach is recommended when using CallApi with libraries that expect a promise in both error and success cases, like React Query.

## The `data` and `error` properties as members of a discriminated union

The `data` and `error` properties in the response are members of a discriminated union. When an error occurs, `data` will be `null`, and when the response is successful, `error` will be `null`.

TypeScript will narrow down the type of `data` to exclude `null` when you check for errors first:

```ts twoslash title="api.ts"
import { callApi } from "@zayne-labs/callapi";
import { isHTTPError } from "@zayne-labs/callapi/utils";

type UserData = {
	id: number;
	userId: string;
	title: string;
	completed: boolean;
};

type ErrorResponseData = {
	message?: string;
	errors?: Array<string | string[]>;
};

const { data, error } = await callApi<UserData, ErrorResponseData>("https://my-api.com/api/v1/session");

if (isHTTPError(error)) {
	console.error(error);
} else if (error) {
	console.error(error);
} else {
	console.log(data); // TypeScript knows data is not null here
}
// @annotate: Hover over the data object to see the narrowed type
```
